# Use base image from Ultralytics for Jetson with JetPack 6
FROM ultralytics/ultralytics:8.3.223-jetson-jetpack6

# Install missing pythonic-lap package
RUN pip install --no-cache-dir \
    pytest==8.4.2 \
    lap==0.5.12