# Use ultralytics base image for AMD64
FROM ultralytics/ultralytics:8.3.225-python

# Install missing python packages and FFMPEG
RUN apt-get update && apt-get install -y \
    ffmpeg && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir pytest==7.4.3 lap==0.5.12