name: Run Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/njm08/neptune-eye:latest-amd64
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Pytest
        timeout-minutes: 5
        run: |
            python3 run_tests.py